import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className=" geist-regular bg-blue-500/10"
      >
        {children}
      </body>
    </html>
  );
}
